### ISSUE TITLE
Nano removed from Chrome? Malware alert?

### ISSUE THREAD

**Issue by Crazierinzane** [jspenguin2017/Snippets#15]
What happened? Chrome disabled Nano Defender and said it was malware. The extension page is now gone.

**Comment by brbsix** [comment]
@Crazierinzane You're weeks too late to the party. Do a Google search or take a look through the many closed issues on this and other related projects. https://www.ghacks.net/2020/10/16/time-to-remove-nano-adblocker-and-defender-from-your-browsers-except-firefox/

**Comment by Crazierinzane** [comment]
Oi, a little late to the draw aren't we, Google?

**Comment by jspenguin2017** [comment]
See the discussion thread [1] or the news article [2]. 

[1] https://github.com/jspenguin2017/Snippets/issues/2
[2] https://arstechnica.com/information-technology/2020/10/popular-chromium-ad-blockers-caught-stealing-user-data-and-accessing-accounts/
