### ISSUE TITLE
I still have Nano Defender

### ISSUE THREAD

**Issue by fosam** [jspenguin2017/Snippets#16]
Hello Hugo!

Thanks for Nano Defender, which i used since it appeared on CWS, now i hear a lot that it got into the wrong hands, i still have the extension installed, i just disabled it right now for security reasons, Chrome does not block it for me, do i need to worry?

![Capture 13_11_2020_21_39_13](https://user-images.githubusercontent.com/52612348/99119141-125b7480-25f9-11eb-84fe-d415267488ef.png)

_**"userResourcesLocation in uBlock"**_

![Capture 13_11_2020_21_37_14](https://user-images.githubusercontent.com/52612348/99119242-3028d980-25f9-11eb-8da6-f8921378d303.png)

![Capture 13_11_2020_21_37_51](https://user-images.githubusercontent.com/52612348/99119323-52225c00-25f9-11eb-8d1c-6f81d4de6859.png)

I see there are some filter updates from time to time, but the numbers never change especially for `Nano Filtes` the number there is always "416 of 416" also after the filter update.

EDIT: Do i need to edit or remove any of these filters? would it be OK to use the filters with uBlock alone in case i must remove Nano Defender?

So, do i need to stop using Nano Defender? should i do any modifications? should i remove it?

What do you think?

Thanks!

**Comment by mapx-** [comment]
Remove it immediately then just install uBO.

**Comment by fosam** [comment]
I already have uBlock only, but it works better with its Defender.
I tried uBlock alone but the i got infested with Anti-Adblock pop-ups. which makes the ad-blocking less effective.
I think it is worth to keep Nano Defender? i mean i haven't experienced anything bad with it (yet).

**Comment by mapx-** [comment]
If you get anti adblock stuff just report it here:
https://github.com/uBlockOrigin/uAssets/issues

where it was always fixed even for defender (99%)

**You have to remove that malware from your system**.

**Comment by fosam** [comment]
What about the those filters, Do i need to edit or remove any of these filters? would it be OK to use the filters with uBlock alone in case i must remove Nano Defender?

**Comment by mapx-** [comment]
1. remove defender malware
2. reset uBO to default settings
3. click "purge all caches" then click "update now"
4. Don't add any of nano lists

**Comment by fosam** [comment]
> where it was always fixed even for defender (99%)

What was getting fixed here for Nano? any more details?

**Comment by jspenguin2017** [comment]
You can find an alternative, install from GitHub, or simply not use it. Depends on what works for you. 
Keep in mind that the GitHub release is the final release, it won't receive any more updates/fixes.

**Comment by fosam** [comment]
Nano does its job, it was more of a question regarding the security of Nano and weather i should be worried or not.
I was thinking of keeping Nano, but based on the recommendations on this discussion, i'll stop using it at this point and settle for uBO alone.
But hey Thanks, it was damn effective while it lasted, (and still is)
