### ISSUE TITLE
Thanks for helping new devs to selling data.

### ISSUE THREAD

**Issue by lilcsz** [jspenguin2017/Snippets#4]
Our all cookies and sessions copied because of you

**Comment by RuggeDX** [comment]
I'm sure the original wouldn't have sold the Nano extensions to the new devs he knew that the new devs would implement this malware. There's no need to put all the blame on the OG dev. Things like this happen, unfortunately. The best thing to do now is to change all your passwords and other sensitive information stored in your browser instead of pointing fingers. 

Hopefully the OG dev and/or Google will investigate.

**Comment by EuphoricPenguin** [comment]
This is absolutely fucked. Why can't we just fork the clean code, and start a new extension from scratch? I'm a chrome web store dev, so I can post direct if we fork and continue. Not to mention, I have a year or two of Node development behind me, so I should be fairly set for doing JS shit.

**Comment by wadawada** [comment]
> This is absolutely fucked. Why can't we just fork the clean code, and start a new extension from scratch? I'm a chrome web store dev, so I can post direct if we fork and continue. Not to mention, I have a year or two of Node development behind me, so I should be fairly set for doing JS shit.

You can fork it any time, but only if you are willing to deal with anti-ads reports sent by users daily. Otherwise, it is the same as using uBlock Origin.

**Comment by native-it** [comment]
This is a wholly unnecessary new thread, opened by a hacker in Turkey no less. Please keep the unproductive spite on Reddit.

**Comment by ChrisFarmer-dev** [comment]
Wait so do they have our login info? Can someone explain to me what all data is stored in cookies and sessions? How dangerous is it ?? Sorry am not an expert. Am just scared that they have our login details (like Gmail and other sites). 😩

**Comment by lilcsz** [comment]
@ChrisFarmer-dev just log out and login again and change passwords

**Comment by OmkarK45** [comment]
Can confirm the breach. My instagram account has been compromised. Change passwords ASAP.

**Comment by ChrisFarmer-dev** [comment]
> @ChrisFarmer-dev just log out and login again and change passwords

Thank you soo much 🙏
