### ISSUE TITLE
Who is new turkish devs?

### ISSUE THREAD

**Issue by lilcsz** [jspenguin2017/Snippets#7]
Give us their name. @jspenguin2017

**Comment by mapx-** [comment]
https://github.com/NanoAdblocker/NanoCore/issues/362#issuecomment-704014156

> llacb47 commented 15 days ago • 
The developers are apparently named semagul aymak and nizametdin altuncu.

Nano Adblocker is controlled by the former and Defender by the latter. I can't find any information about them.

But ... probably are fake names

**Comment by lilcsz** [comment]
I'm living at Turkey names looks like real

**Comment by lilcsz** [comment]
Also police can find them on tracking URL and payment method

**Comment by tweedge** [comment]
@jspenguin2017 do not release that information publicly. You don't want users to brigade the authors and give them a good sense of what tracks need to be covered. Only disclose this information to law enforcement.
